### ISSUE TITLE
GPU regression tests

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#451] opened 2021-08-11 00:33 UTC
Got errors from GPU regression tests on lassen; small difference with the AIR runs

```
/g/g92/li50/workspace/hypre/test/AUTOTEST/machine-lassen.dir/basic-cuda-um.dir/run.dir/TEST_ij/air.err
/g/g92/li50/workspace/hypre/test/AUTOTEST/machine-lassen.dir/basic-cuda-um-mixedint.dir/run.dir/TEST_ij/air.err
```

```(7) - Final Relative Residual Norm = 3.559160e-09
(7) + Final Relative Residual Norm = 9.341004e-09      (err 5.78e-09)

(11) - Final Relative Residual Norm = 7.741289e-09
(11) + Final Relative Residual Norm = 8.979894e-09      (err 1.24e-09)

(19) - Final GMRES Relative Residual Norm = 1.606807e-09
(19) + Final GMRES Relative Residual Norm = 1.495148e-09      (err 1.12e-10)

(23) - Final GMRES Relative Residual Norm = 3.288903e-09
(23) + Final GMRES Relative Residual Norm = 2.401543e-09      (err 8.87e-10)

(7) - Final Relative Residual Norm = 3.559160e-09
(7) + Final Relative Residual Norm = 9.341004e-09      (err 5.78e-09)

(11) - Final Relative Residual Norm = 7.741289e-09
(11) + Final Relative Residual Norm = 8.979894e-09      (err 1.24e-09)

(19) - Final GMRES Relative Residual Norm = 1.606807e-09
(19) + Final GMRES Relative Residual Norm = 1.495148e-09      (err 1.12e-10)

(23) - Final GMRES Relative Residual Norm = 3.288903e-09
(23) + Final GMRES Relative Residual Norm = 2.401543e-09      (err 8.87e-10)
```
@waynemitchell Can we just change the `.saved.lassen`?  Thanks!

**Comment by waynemitchell** [comment] 2021-08-11 15:33
@liruipeng I just ran with a clean build of master and got these same results. Not sure what changed... Do you have any ideas why small differences like this might occur? I'm fine with just updating the .saved.lassen file.

**Comment by liruipeng** [comment] 2021-08-11 15:59
> @liruipeng I just ran with a clean build of master and got these same results. Not sure what changed... Do you have any ideas why small differences like this might occur? I'm fine with just updating the .saved.lassen file.

When did you generate the `.saved`, and how (running `machine-lassen.sh` or manually run the jobs? on how many nodes?)? Thanks!

**Comment by waynemitchell** [comment] 2021-08-11 18:58
> > @liruipeng I just ran with a clean build of master and got these same results. Not sure what changed... Do you have any ideas why small differences like this might occur? I'm fine with just updating the .saved.lassen file.
> 
> When did you generate the `.saved`, and how (running `machine-lassen.sh` or manually run the jobs? on how many nodes?)? Thanks!

I generated the .saved results using the runtests.sh script in the tests directory with the corresponding air.sh/air.jobs files via:
./runtests -t TEST_ij/air.sh
Then rename the output in TEST_ij:
mv air.out air.saved
I did this on quartz for the CPU run and lassen for the GPU .saved.lassen run. This was all single node (lalloc 1 ...). I guess I would have to restore the branch to look at the commit history to see exactly when the .saved files were generated, but I don't think it was many commits ago. In fact, I am pretty sure I was getting exact agreement with the current .saved files when I did the original Air gpu PR merge (before the recent fixes were merged), but I'd have to double check.

**Comment by liruipeng** [comment] 2021-08-11 19:06
@waynemitchell Thanks for clarifying. We recently found number of nodes can also change results. GPU regression test uses 4 nodes. https://github.com/hypre-space/autotest/blob/2130f57b98d85997e33849a830c164dd8014baff/test-lassen.sh#L16

**Comment by waynemitchell** [comment] 2021-08-11 22:11
@liruipeng OK, I've put in a new PR for this. I was unable to reproduce the results in the current air.saved.lassen file even if I backed up to the commit where the Air gpu PR was merged in. I guess the code must have had some kind of small change or fix since I initially generate those results.

**Closed as completed** 2021-08-11 22:18 UTC
