### ISSUE TITLE
Rename version script

### ISSUE THREAD

**Issue by adayton1** [hypre-space/hypre#536] opened 2021-12-01 18:45 UTC
We've experienced some conflicts with the src/utilities/version script. It turns out <version> is a header used by boost (and it will also be part of the std library in C++20, see https://en.cppreference.com/w/cpp/header/version), and since src/utilities gets added to the path, the version script is accidentally included instead of the <version> header.

Can the version script be renamed to version.sh and/or perhaps moved into a separate directory that doesn't have any headers in it?

**Comment by rfalgout** [comment] 2021-12-01 18:56
There is a long discussion about this in Issue #513.  The problem is the monolithic approach for compiling, which isn't scalable or maintainable.  You should not point to any of the source directories in hypre when compiling.

**Comment by victorapm** [comment] 2023-03-19 22:55
Closing this issue since it has been resolved with #731

**Closed as completed by victorapm** 2023-03-19 22:55 UTC
